services:
  mysql:
    image: mysql:8
    ports: ['3306:3306']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: alice
      MYSQL_PASSWORD: s3cret
      MYSQL_DATABASE: foobar_db
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
